# Generated by Django 5.2 on 2025-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_page_audio_label_alter_page_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
