# Generated by Django 5.2 on 2025-04-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_page_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='label',
        ),
    ]
